$config['plugins'] = array_values(array_unique(array_merge($config['plugins'] ?? [], ['archive', 'zipdownload', 'lostandfound_bridge'])));
$config['product_name'] = 'Lost & Found Webmail';
$config['language'] = 'en_US';
$config['language_selector'] = false;
$config['enable_installer'] = false;
$config['session_lifetime'] = 28800;
$config['des_key'] = getenv('ROUNDCUBE_DES_KEY') ?: hash('sha256', getenv('ROUNDCUBE_SHARED_SECRET') ?: 'lostfound-roundcube');
$config['lostandfound_bridge_app_url'] = rtrim(getenv('LAF_APP_INTERNAL_URL') ?: 'http://app:8000', '/');
$config['lostandfound_bridge_shared_secret'] = getenv('ROUNDCUBE_SHARED_SECRET') ?: '';
